name: CI/CD Pipeline for Dockerized Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} .

      # Debug: List Docker images after build
      - name: List Docker Images
        run: docker images

      # Run tests inside the Docker container
      - name: Run Tests
        run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} pytest

  push-and-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()

    steps:
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker image
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

      # Debug: Verify kubeconfig file
      - name: Verify kubeconfig file
        run: |
          echo "${{ secrets.KUBECONFIG_SECRET }}" > kubeconfig
          cat kubeconfig

      # Set up kubeconfig
      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_SECRET }}" > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig
          echo "Kubeconfig setup complete"

      # Apply Kubernetes Deployment
      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s-deployment.yaml

      # Verify Deployment
      - name: Verify Deployment
        run: kubectl get pods
