name: CI/CD Pipeline for Kubernetes

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write kubeconfig file
        run: |
          echo "${{ secrets.KUBECONFIG_SECRET }}" > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig
          echo "Kubeconfig written to: $KUBECONFIG"
          echo "Contents of kubeconfig:"
          cat kubeconfig

      - name: Verify Kubeconfig
        run: |
          kubectl config view
          kubectl get nodes

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s-deployment.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG_SECRET }}
