name: CI/CD Pipeline for Dockerized Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        id: build-image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          docker images

      - name: Run Tests
        run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} pytest

  push-and-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Retag and Push Docker Image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_SECRET }}" | base64 --decode > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig
          echo "Kubeconfig written to: $KUBECONFIG"
          echo "Contents of kubeconfig:"
          cat kubeconfig

      - name: Verify kubeconfig
        run: |
          echo "Current kubectl context:"
          kubectl config current-context
          echo "Clusters available:"
          kubectl config get-clusters
          echo "Getting nodes:"
          kubectl get nodes

      - name: Apply Kubernetes Deployment
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}|" k8s-deployment.yaml
          kubectl apply -f k8s-deployment.yaml
          echo "Verifying pods..."
          kubectl get pods

      - name: Verify Deployment
        run: |
          echo "Getting services..."
          kubectl get services
          echo "Getting pods..."
          kubectl get pods
