name: CI/CD Pipeline for Dockerized Application with Minikube

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack curl

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          sudo minikube start --driver=none
          sudo minikube status

      - name: Set Up kubectl
        run: |
          echo "Setting up kubectl configuration"
          sudo minikube update-context
          kubectl version --client
          kubectl cluster-info

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        id: build-image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker images

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

      - name: Run Tests
        run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} pytest

  push-and-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack curl

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          sudo minikube start --driver=none
          sudo minikube status

      - name: Set Up kubectl
        run: |
          echo "Setting up kubectl configuration"
          sudo minikube update-context
          kubectl version --client
          kubectl cluster-info

      - name: Pull and Retag Docker Image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      - name: Deploy to Kubernetes
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}|" k8s-deployment.yaml
          kubectl apply -f k8s-deployment.yaml
          kubectl get pods
          kubectl get services
