name: CI/CD Pipeline for Kubernetes Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Necessary Tools
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack curl wget containernetworking-plugins cri-tools

          # Install Minikube
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

          # Install Compatible Go Version
          GO_VERSION="1.21.0"
          curl -LO https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin

          # Install cri-dockerd
          git clone https://github.com/Mirantis/cri-dockerd.git
          cd cri-dockerd
          mkdir bin
          /usr/local/go/bin/go build -o bin/cri-dockerd
          sudo mv bin/cri-dockerd /usr/local/bin/
          sudo cp -a packaging/systemd/* /etc/systemd/system
          sudo systemctl daemon-reload
          sudo systemctl enable cri-docker.socket
          sudo systemctl start cri-docker.socket
          cd ..
          rm -rf cri-dockerd

      # Step 3: Start Minikube
      - name: Start Minikube
        run: |
          sudo minikube start --driver=none
          sudo minikube update-context

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/my-app
          GIT_SHA=${{ github.sha }}
          docker build -t $IMAGE_NAME:$GIT_SHA .
          docker push $IMAGE_NAME:$GIT_SHA
          docker tag $IMAGE_NAME:$GIT_SHA $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

      # Step 5: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          export KUBECONFIG=$(sudo minikube kubeconfig)

          # Apply Kubernetes manifests
          kubectl apply -f k8s-deployment.yaml --validate=false

          # Check Deployment Status
          kubectl rollout status deployment/my-app

      # Step 6: Verify Deployment
      - name: Verify Kubernetes Deployment
        run: |
          kubectl get pods
          kubectl get services
