name: CI/CD Pipeline for Dockerized Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Debug GitHub SHA
      - name: Debug GitHub SHA
        run: |
          echo "GitHub SHA: ${{ github.sha }}"

      # Step 5: Build Docker Image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} .

      # Step 6: Verify Docker Image
      - name: Verify Docker Image
        run: docker images

      # Step 7: Run Tests
      - name: Run Tests
        run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} pytest

      # Step 8: Push Docker Image
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

  deploy-to-kubernetes:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: success()

    steps:
      # Step 1: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 2: Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.26.0"

      # Step 3: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s-deployment.yaml

  rollback:
    needs: deploy-to-kubernetes
    runs-on: ubuntu-latest
    if: failure()

    steps:
      # Rollback Kubernetes Deployment
      - name: Rollback Deployment
        run: kubectl rollout undo deployment my-app
