name: CI/CD Pipeline with WSL2

on:
  push:
    branches:
      - master

jobs:
  setup-and-build:
    runs-on: windows-latest

    steps:
      - name: Setup WSL
        run: |
          # Enable WSL and Virtual Machine Platform
          dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
          dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
          wsl --update || echo "WSL update failed, continuing..."
          wsl --install -d Ubuntu || echo "Ubuntu already installed or WSL misconfigured"
          wsl --list --online || echo "Check WSL setup manually if no distributions are listed"
          wsl --set-default-version 2 || echo "Failed to set WSL2 as default"

      - name: Setup Dependencies in WSL
        run: |
          wsl -d Ubuntu -- bash -c "
          sudo apt-get update &&
          sudo apt-get install -y curl wget conntrack &&
          CNI_VERSION='v1.2.0' &&
          wget https://github.com/containernetworking/plugins/releases/download/\$CNI_VERSION/cni-plugins-linux-amd64-\$CNI_VERSION.tgz &&
          sudo mkdir -p /opt/cni/bin &&
          sudo tar -xvf cni-plugins-linux-amd64-\$CNI_VERSION.tgz -C /opt/cni/bin &&
          rm -f cni-plugins-linux-amd64-\$CNI_VERSION.tgz &&
          CRICTL_VERSION='v1.25.0' &&
          wget https://github.com/kubernetes-sigs/cri-tools/releases/download/\$CRICTL_VERSION/crictl-\$CRICTL_VERSION-linux-amd64.tar.gz &&
          sudo tar -xvf crictl-\$CRICTL_VERSION-linux-amd64.tar.gz -C /usr/local/bin &&
          rm -f crictl-\$CRICTL_VERSION-linux-amd64.tar.gz &&
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 &&
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          "

      - name: Start Minikube
        run: |
          wsl -d Ubuntu -- bash -c "
          sudo minikube start --driver=none &&
          sudo minikube update-context
          "
